version: 2
jobs:
  build:
    docker:
      - image: solarwinds/prometheus2appoptics:0.1_ci
    working_directory: /go/src/github.com/solarwinds/prometheus2appoptics
    steps:
      - checkout
      - run: dep ensure
      - run: make test
